runtime: php55
api_version: 1

handlers:
- url: /(.+\.(html|css|gif|png|jpg))$
  static_files: \1
  upload: .+\.(html|css|gif|png|jpg)$
  application_readable: true
  
- url: /(.+\.php)$
  script: \1
  
- url: /.*
  static_files: index.html
  upload: index.html
  application_readable: true

 
 
 